version: '3.4'

services:
  mongo:
    image: "${REGISTRY_NAME}mongo:latest"
    volumes:
      - mongo_data:/data/db
    networks:
      - "internal"
    restart: "unless-stopped"

  elastic:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    image: "${REGISTRY_NAME}devclubiitd/elasticsearch:0.1"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200 # Need to expose for frontend
    networks:
      - "internal"
    restart: "unless-stopped"

  crawler:
    build: 
      context: ./crawler
      dockerfile: Dockerfile
    image: "${REGISTRY_NAME}devclubiitd/haystack_crawler:0.1"
    restart: "unless-stopped"
    networks:
      - "internal"
      - "reverseproxy"
    env_file:
      - crawler/.env
    environment:
      - MONGODB_URI=mongo:27017
      - ELASTIC_URI=elastic:9200
    depends_on:
      - mongo
      - elastic

volumes:
  mongo_data:
  elastic_data:

networks:
  reverseproxy:
    external:
      name: "reverseproxy"
  internal: